from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from PySide6.QtCore import QByteArray, QSize, Qt, QUrl
from PySide6.QtGui import QDesktopServices
from PySide6.QtWidgets import (
    QAbstractItemView,
    QComboBox,
    QFrame,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QPushButton,
    QScrollArea,
    QSizePolicy,
    QSplitter,
    QStackedWidget,
    QTreeWidget,
    QTreeWidgetItem,
    QVBoxLayout,
    QWidget,
)

from dlc_gait_assembly.gui.gait_analysis.previews import ClickableSvgWidget, SvgPreviewDialog
from dlc_gait_assembly.gui.shared.svg import qt_safe_svg_bytes
from dlc_gait_assembly.services.pipeline.gait_parameter_catalog import (
    GaitParameterDefinition,
    gait_parameter_catalog,
)
from dlc_gait_assembly.services.pipeline.rustlab1.extraction import (
    RUSTLAB1_FORELIMB_PARAMETER_NAMES,
)
from dlc_gait_assembly.services.project_paths import find_project_root


@dataclass(frozen=True)
class FigureDefinition:
    source: str
    filename: str
    title: str
    purpose: str
    shows: str
    interpretation: str
    provenance: str
    asset_path: Path
    documentation_url: str


def gait_figure_catalog(project_root: Path | None = None) -> tuple[FigureDefinition, ...]:
    """Describe every non-PCA/RF figure created by the ALMA and RustLab1 workflows."""

    root = project_root or find_project_root(__file__)
    preview_root = root / "assets" / "analysis_previews"
    alma_root = preview_root / "alma_reference_alma_figures"
    rustlab_root = preview_root / "rustlab1"
    alma_docs = "https://github.com/sollan/alma"
    rustlab_docs = "https://github.com/rustlab1/DLC-Gait-Analysis"

    def alma(filename, title, purpose, shows, interpretation):
        return FigureDefinition(
            "ALMA",
            filename,
            title,
            purpose,
            shows,
            interpretation,
            "Generated by DLC Gait Assembler from ALMA's official treadmill demo parameter table (30 cm/s).",
            alma_root / filename,
            alma_docs,
        )

    def rustlab(filename, title, purpose, shows, interpretation):
        return FigureDefinition(
            "RustLab1",
            filename,
            title,
            purpose,
            shows,
            interpretation,
            "Rendered at 2400 px from the official RustLab1 representative baseline and 3-days-post-injury runway sample outputs.",
            rustlab_root / filename,
            rustlab_docs,
        )

    return (
        alma(
            "1_ALMA_cycle_timing.svg",
            "Gait-cycle timing",
            "Summarizes how each detected stride is divided between stance and swing.",
            "Cycle, stance, and swing durations plus stance percentage, grouped by hindlimb when available.",
            "Use it to compare temporal balance between limbs and to spot unusually long or short cycles.",
        ),
        alma(
            "2_ALMA_spatiotemporal_profile.svg",
            "Spatiotemporal profile",
            "Provides a compact overview of stride geometry and swing performance.",
            "Stride length, step height, maximum swing velocity, and mean toe-to-iliac-crest distance.",
            "Shifts in box positions show systematic gait differences; wide boxes or distant points indicate cycle variability.",
        ),
        alma(
            "3_ALMA_joint_kinematics.svg",
            "Joint kinematics",
            "Compares the working range of the MTP, ankle, knee, and hip.",
            "Flexion, extension, and angular amplitude summaries for each joint.",
            "Amplitude reflects range of motion. Read flexion and extension together before interpreting a change in amplitude.",
        ),
        alma(
            "4_ALMA_cycle_trends.svg",
            "Parameters across cycles",
            "Shows whether key measurements remain stable through the recording.",
            "Stride length, step height, stance percentage, and knee amplitude in gait-cycle order.",
            "Gradual slopes can reveal drift or fatigue-like changes; isolated peaks are useful quality-control targets.",
        ),
        alma(
            "5_ALMA_parameter_heatmap.svg",
            "Standardized parameter heatmap",
            "Makes multi-parameter cycle patterns visible on one shared scale.",
            "The highest-variance numeric parameters standardized as z-scores for every detected gait cycle.",
            "Warm and cool cells mean above- and below-recording averages, not different physical units or absolute severity.",
        ),
        alma(
            "6_ALMA_parameter_correlation.svg",
            "Parameter correlation",
            "Highlights measurements that change together across gait cycles.",
            "A Spearman correlation matrix for the highest-variance numeric parameters.",
            "Values near +1 or -1 indicate strong monotonic relationships; correlation alone does not establish cause.",
        ),
        alma(
            "7_ALMA_variability.svg",
            "Stride variability",
            "Summarizes cycle-to-cycle consistency of endpoint trajectories.",
            "ALMA's x-, y-, and combined-plane variability measurements over multi-stride windows.",
            "Higher values indicate less repeatable trajectories, but should be checked against tracking quality and cycle count.",
        ),
        alma(
            "8_ALMA_drag_profile.svg",
            "Toe-drag profile",
            "Summarizes detected low-clearance portions of swing.",
            "Drag duration and drag percentage for each accepted gait cycle.",
            "Interpret it with the configured clearance and consecutive-frame thresholds, since those define a drag event.",
        ),
        rustlab(
            "1_PLOT_bar_all_videos.svg",
            "Tracking reliability by video",
            "Checks the amount of confident DLC tracking before gait measurements are interpreted.",
            "The proportion of samples meeting the likelihood criterion across the representative runway recordings.",
            "Lower bars identify recordings that may need marker review or stricter exclusion before group comparisons.",
        ),
        rustlab(
            "2_PLOT_Donut_Summary_Validation.svg",
            "Tracking validation summary",
            "Condenses accepted versus rejected tracking into a quick quality-control view.",
            "The valid and invalid portions of the official representative sample after likelihood validation.",
            "A smaller valid segment signals that downstream timing and position measurements need extra scrutiny.",
        ),
        rustlab(
            "3_1_PLOT_control_for_outliers_before.svg",
            "Coordinate QC — before filtering",
            "Exposes raw coordinate spread and obvious tracking outliers.",
            "Marker coordinates from the representative sample before likelihood-based filtering.",
            "Remote clusters or implausible ranges suggest mislabeled or occluded points that should not drive gait metrics.",
        ),
        rustlab(
            "3_2_PLOT_control_for_outliers_after.svg",
            "Coordinate QC — after filtering",
            "Shows the coordinate data retained for analysis after reliability filtering.",
            "The same marker-coordinate overview after low-confidence observations are removed.",
            "Compare this with the raw panel to confirm outliers were reduced without erasing the expected movement path.",
        ),
        rustlab(
            "4_1_PLOT_Overview_Distribution_X.svg",
            "X-coordinate distribution",
            "Checks horizontal tracking coverage and unexpected position clusters.",
            "Distributions of filtered x coordinates across tracked markers and recordings.",
            "Separated or unusually broad distributions can indicate view alignment differences, drift, or remaining outliers.",
        ),
        rustlab(
            "4_2_PLOT_Overview_Distribution_Y.svg",
            "Y-coordinate distribution",
            "Checks vertical tracking coverage and unexpected height clusters.",
            "Distributions of filtered y coordinates across tracked markers and recordings.",
            "Use view-specific coordinate direction when reading height; image y often increases downward.",
        ),
        rustlab(
            "5_PLOT_overview_steps.svg",
            "Normalized marker overview",
            "Provides a camera-normalized overview of the tracked runway movement.",
            "Representative marker trajectories and step structure after coordinate normalization.",
            "Look for coherent paths and repeated step shapes; discontinuities usually merit frame-level inspection.",
        ),
        rustlab(
            "6_1_PLOT_DOWN_Analysis_Speed_QC.svg",
            "Down-view paw-speed QC",
            "Supports the speed-based separation of stance and swing phases.",
            "Hindpaw speed, plus forepaw speed in Hindlimb + Forelimb mode, in the bottom camera view.",
            "Low-speed regions correspond to stance candidates and higher-speed regions to swing candidates; noisy transitions reduce segmentation confidence.",
        ),
        rustlab(
            "6_2_sync_plots.svg",
            "Gait-cycle synchronization",
            "Compares gait-cycle timing and, in the combined mode, diagonal fore–hind coordination.",
            "Cycle duration, stride length, stance/swing timing, and FL–BR and FR–BL asynchronous-phase fractions when forelimbs are enabled.",
            "Higher diagonal asynchronous-phase fractions mean the paired forepaw and hindpaw spend more analyzed frames in opposing phases.",
        ),
        rustlab(
            "7_1_PLOT_FIRST_OVERVIEW_VERTICAL_BARPLOT.svg",
            "Vertical-height summary",
            "Summarizes lateral-view marker height and movement across groups.",
            "Side-view hindlimb measures and, when enabled, forepaw, wrist, elbow, and shoulder height/excursion measures.",
            "Use the summary to locate group differences, then inspect the timecourse to see when they occur.",
        ),
        rustlab(
            "7.2_PLOT_SECOND_OVERVIEW_Vertical_TIMECOURSE.svg",
            "Vertical-height timecourse",
            "Shows how lateral marker heights evolve throughout each representative run.",
            "Gait-cycle-ordered vertical measures for hindlimb markers and optional forelimb markers.",
            "Repeated oscillations should align with steps; abrupt jumps often reflect tracking artifacts rather than gait.",
        ),
        rustlab(
            "8_1_PLOT_Horizontal_Analysis_QC.svg",
            "Paw-position QC",
            "Checks horizontal paw position before protraction and retraction are summarized.",
            "Hindpaw position relative to hip and optional forepaw position relative to shoulder.",
            "Consistent periodic excursions support the derived movement measures; discontinuities should be reviewed.",
        ),
        rustlab(
            "8.2_PLOT_Protraction_Retraction.svg",
            "Protraction/retraction summary",
            "Summarizes forward and backward hindlimb and optional forelimb excursion.",
            "Protraction, retraction, average, and median horizontal paw-position measures by side and limb.",
            "Read forward and backward excursions together to distinguish a translated step from a changed movement range.",
        ),
        rustlab(
            "8_3_PLOT_Protraction_Retraction_line.svg",
            "Protraction/retraction timecourse",
            "Shows the sequence underlying the horizontal excursion summary.",
            "Hindpaw and optional forepaw horizontal position across gait cycles.",
            "Peaks and troughs mark opposing excursion phases; irregular spacing can indicate variable stepping or tracking loss.",
        ),
        rustlab(
            "9_1_PLOT_DURATION_of_STEPE.svg",
            "Step duration",
            "Compares how long detected steps last.",
            "ALMA hindlimb cycle durations and optional RustLab1 forelimb stance-onset intervals.",
            "Interpret very short or long values alongside the paw-speed plot to rule out split or merged step events.",
        ),
        rustlab(
            "9_2_PLOT_Distance_covered_per_step.svg",
            "Distance per step",
            "Compares horizontal distance covered by each detected hindlimb step.",
            "Per-step movement distance from the down-view tracking coordinates.",
            "Lower distances can reflect shorter steps, but calibration, direction, and tracking quality should be checked first.",
        ),
        rustlab(
            "10_1_PLOT_selected_horizontal_Angle.svg",
            "Paw and forelimb-angle timecourse",
            "Shows frame-by-frame paw orientation and optional forelimb joint kinematics.",
            "Bottom-view hind/forepaw angles plus side-view elbow and wrist angles when forelimbs are enabled.",
            "Smooth repeated changes are expected through stepping; abrupt angle flips usually indicate coordinate problems.",
        ),
        rustlab(
            "10_2_PLOT_horizontal_Angle_line.svg",
            "Paw and forelimb-angle summary",
            "Compares paw orientation and optional forelimb joint angles across gait cycles.",
            "Mean, 95th-percentile, and 10th-percentile summaries for bottom-view paws and side-view forelimb joints.",
            "Side-to-side or day-to-day shifts indicate changed orientation only after view alignment and tracking QC are confirmed.",
        ),
    )


class GaitParameterReferenceWidget(QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("GaitParameterReference")
        self._definitions = gait_parameter_catalog()
        self._figure_definitions = gait_figure_catalog()
        self._visible_definitions: list[GaitParameterDefinition] = []
        self._visible_figures: list[FigureDefinition] = []
        self._selected_figure: FigureDefinition | None = None
        self._large_figure_dialog: SvgPreviewDialog | None = None
        self._build_ui()
        self._connect_signals()
        self._apply_figure_filter()
        self._apply_filter()

    def set_multiside(self, multiside: bool) -> None:
        """Show only the parameter definitions valid for the active input mode."""
        self.view_filter.setCurrentText("Multi-view" if multiside else "Single-view")

    def show_figure_documentation(self) -> None:
        self.documentation_stack.setCurrentWidget(self.figure_documentation)

    def show_parameter_documentation(self) -> None:
        self.documentation_stack.setCurrentWidget(self.parameter_documentation)

    def _build_ui(self) -> None:
        root = QVBoxLayout(self)
        root.setContentsMargins(0, 0, 0, 0)
        root.setSpacing(0)
        self.documentation_stack = QStackedWidget()
        self.documentation_stack.setObjectName("GaitDocumentationStack")
        root.addWidget(self.documentation_stack, 1)

        self.figure_documentation = self._build_figure_documentation()
        self.parameter_documentation = QWidget()
        self.parameter_documentation.setObjectName("ParameterDocumentation")
        self.documentation_stack.addWidget(self.figure_documentation)
        self.documentation_stack.addWidget(self.parameter_documentation)
        self.show_parameter_documentation()

        documentation = QVBoxLayout(self.parameter_documentation)
        documentation.setContentsMargins(20, 18, 20, 20)
        documentation.setSpacing(10)

        title = QLabel("Gait parameter reference")
        title.setObjectName("ParameterReferenceTitle")
        documentation.addWidget(title)
        subtitle = QLabel(
            "Browse the measurements available in generated parameter tables. "
            "Select a row to see its calculation and input requirements."
        )
        subtitle.setObjectName("ParameterReferenceSubtitle")
        subtitle.setWordWrap(True)
        documentation.addWidget(subtitle)

        controls = QHBoxLayout()
        controls.setSpacing(10)
        self.search_edit = QLineEdit()
        self.search_edit.setObjectName("ParameterSearch")
        self.search_edit.setPlaceholderText("Search parameters, calculations, sources, or markers")
        self.search_edit.setClearButtonEnabled(True)
        controls.addWidget(self.search_edit, 1)
        self.view_filter = QComboBox()
        self.view_filter.setObjectName("ParameterViewFilter")
        self.view_filter.addItems(("All views", "Single-view", "Multi-view"))
        controls.addWidget(self.view_filter)
        self.source_filter = QComboBox()
        self.source_filter.setObjectName("ParameterSourceFilter")
        self.source_filter.addItems(("All sources", "ALMA", "RustLab1", "Custom SOP"))
        controls.addWidget(self.source_filter)
        documentation.addLayout(controls)

        self.count_label = QLabel()
        self.count_label.setObjectName("MutedLabel")
        documentation.addWidget(self.count_label)

        self.parameter_splitter = QSplitter(Qt.Horizontal)
        self.parameter_splitter.setChildrenCollapsible(False)
        documentation.addWidget(self.parameter_splitter, 1)

        self.parameter_tree = QTreeWidget()
        self.parameter_tree.setObjectName("GaitParameterTree")
        self.parameter_tree.setHeaderLabels(("#", "Parameter", "Calculation", "Source", "View type", "Required view"))
        self.parameter_tree.setRootIsDecorated(False)
        self.parameter_tree.setAlternatingRowColors(True)
        self.parameter_tree.setWordWrap(True)
        self.parameter_tree.setTextElideMode(Qt.ElideNone)
        self.parameter_tree.setUniformRowHeights(False)
        self.parameter_tree.header().setSectionResizeMode(0, QHeaderView.ResizeToContents)
        self.parameter_tree.header().setSectionResizeMode(1, QHeaderView.Stretch)
        self.parameter_tree.header().setSectionResizeMode(2, QHeaderView.Stretch)
        self.parameter_tree.header().setSectionResizeMode(3, QHeaderView.ResizeToContents)
        self.parameter_tree.header().setSectionResizeMode(4, QHeaderView.ResizeToContents)
        self.parameter_tree.header().setSectionResizeMode(5, QHeaderView.ResizeToContents)
        self.parameter_splitter.addWidget(self.parameter_tree)

        details = QFrame()
        details.setObjectName("ParameterDetails")
        details.setMinimumWidth(330)
        details_layout = QVBoxLayout(details)
        details_layout.setContentsMargins(18, 18, 18, 18)
        details_layout.setSpacing(12)
        self.name_label = QLabel("Select a parameter")
        self.name_label.setObjectName("ParameterName")
        self.name_label.setWordWrap(True)
        details_layout.addWidget(self.name_label)
        calculation_heading = QLabel("Calculation")
        calculation_heading.setObjectName("ParameterDetailHeading")
        details_layout.addWidget(calculation_heading)
        self.calculation_label = QLabel()
        self.calculation_label.setObjectName("ParameterCalculationFocus")
        self.calculation_label.setWordWrap(True)
        self.calculation_label.setTextInteractionFlags(Qt.TextSelectableByMouse)
        details_layout.addWidget(self.calculation_label)
        self.identifier_label = _detail_label(details_layout, "Output column")
        self.views_label = _detail_label(details_layout, "Views")
        self.markers_label = _detail_label(details_layout, "Required markers")
        details_layout.addStretch(1)
        self.parameter_splitter.addWidget(details)
        self.parameter_splitter.setStretchFactor(0, 4)
        self.parameter_splitter.setStretchFactor(1, 1)
        self.parameter_splitter.setSizes((1040, 340))

    def _build_figure_documentation(self) -> QWidget:
        panel = QWidget()
        panel.setObjectName("FigureDocumentation")
        layout = QVBoxLayout(panel)
        layout.setContentsMargins(20, 18, 20, 20)
        layout.setSpacing(10)

        heading = QLabel("Figure creator documentation")
        heading.setObjectName("FigureCreatorTitle")
        layout.addWidget(heading)
        intro = QLabel(
            "Preview every ALMA and RustLab1 figure created by the gait workflow. "
            "Each preview uses real project sample data and opens at full size when clicked. "
            "PCA and random-forest figures are excluded."
        )
        intro.setObjectName("FigureCreatorIntro")
        intro.setWordWrap(True)
        layout.addWidget(intro)

        filter_row = QHBoxLayout()
        filter_row.setSpacing(8)
        self.figure_source_filter = QComboBox()
        self.figure_source_filter.setObjectName("FigureSourceFilter")
        self.figure_source_filter.addItems(("All figures", "ALMA", "RustLab1"))
        filter_row.addWidget(self.figure_source_filter, 1)
        self.figure_count_label = QLabel()
        self.figure_count_label.setObjectName("FigureCountLabel")
        filter_row.addWidget(self.figure_count_label)
        layout.addLayout(filter_row)

        content = QSplitter(Qt.Horizontal)
        content.setObjectName("FigureDocumentationSplitter")
        content.setChildrenCollapsible(False)
        layout.addWidget(content, 1)

        index_panel = QFrame()
        index_panel.setObjectName("FigureCreatorIndex")
        index_panel.setMinimumWidth(330)
        index_layout = QVBoxLayout(index_panel)
        index_layout.setContentsMargins(12, 12, 12, 12)
        index_layout.setSpacing(8)
        index_heading = QLabel("Available figures")
        index_heading.setObjectName("FigureIndexHeading")
        index_layout.addWidget(index_heading)
        self.figure_list = QListWidget()
        self.figure_list.setObjectName("FigureCreatorList")
        self.figure_list.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.figure_list.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.figure_list.setTextElideMode(Qt.ElideRight)
        index_layout.addWidget(self.figure_list, 1)
        content.addWidget(index_panel)

        detail_panel = QFrame()
        detail_panel.setObjectName("FigureCreatorDetails")
        detail_layout = QVBoxLayout(detail_panel)
        detail_layout.setContentsMargins(16, 14, 16, 14)
        detail_layout.setSpacing(9)

        detail_header = QHBoxLayout()
        self.figure_title_label = QLabel("Select a figure")
        self.figure_title_label.setObjectName("FigureExplanationTitle")
        self.figure_title_label.setWordWrap(True)
        detail_header.addWidget(self.figure_title_label, 1)
        self.figure_source_badge = QLabel()
        self.figure_source_badge.setObjectName("FigureSourceBadge")
        detail_header.addWidget(self.figure_source_badge)
        detail_layout.addLayout(detail_header)

        self.figure_preview = ClickableSvgWidget()
        self.figure_preview.setObjectName("FigureCreatorPreview")
        self.figure_preview.setMinimumSize(360, 210)
        self.figure_preview.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        detail_layout.addWidget(self.figure_preview, 3)

        preview_actions = QHBoxLayout()
        preview_note = QLabel("Original proportions preserved")
        preview_note.setObjectName("FigurePreviewNote")
        preview_actions.addWidget(preview_note)
        preview_actions.addStretch(1)
        self.open_figure_button = QPushButton("Open large preview")
        self.open_figure_button.setObjectName("OpenFigurePreview")
        preview_actions.addWidget(self.open_figure_button)
        detail_layout.addLayout(preview_actions)

        explanation_scroll = QScrollArea()
        explanation_scroll.setObjectName("FigureExplanationScroll")
        explanation_scroll.setWidgetResizable(True)
        explanation_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        explanation_scroll.setMinimumHeight(110)
        explanation = QWidget()
        explanation_layout = QVBoxLayout(explanation)
        explanation_layout.setContentsMargins(0, 0, 7, 0)
        explanation_layout.setSpacing(6)
        self.figure_purpose_label = _figure_detail_label(explanation_layout, "Purpose")
        self.figure_shows_label = _figure_detail_label(explanation_layout, "What it shows")
        self.figure_interpretation_label = _figure_detail_label(explanation_layout, "How to read it")
        self.figure_provenance_label = _figure_detail_label(explanation_layout, "Real-data source")
        explanation_layout.addStretch(1)
        explanation_scroll.setWidget(explanation)
        detail_layout.addWidget(explanation_scroll, 1)

        self.figure_docs_button = QPushButton("Open source documentation")
        self.figure_docs_button.setObjectName("FigureDocsButton")
        detail_layout.addWidget(self.figure_docs_button)
        content.addWidget(detail_panel)
        content.setStretchFactor(0, 0)
        content.setStretchFactor(1, 1)
        content.setSizes((350, 990))
        return panel

    def _connect_signals(self) -> None:
        self.search_edit.textChanged.connect(self._apply_filter)
        self.view_filter.currentTextChanged.connect(self._apply_filter)
        self.source_filter.currentTextChanged.connect(self._apply_filter)
        self.parameter_tree.currentItemChanged.connect(self._selection_changed)
        self.figure_source_filter.currentTextChanged.connect(self._apply_figure_filter)
        self.figure_list.currentItemChanged.connect(self._figure_selection_changed)
        self.figure_preview.clicked.connect(self._show_large_figure)
        self.open_figure_button.clicked.connect(self._show_large_figure)
        self.figure_docs_button.clicked.connect(self._open_figure_documentation)

    def _apply_figure_filter(self) -> None:
        source = self.figure_source_filter.currentText()
        current_filename = self._selected_figure.filename if self._selected_figure else ""
        self.figure_list.clear()
        self._visible_figures = []
        selected_item = None
        for figure in self._figure_definitions:
            if source != "All figures" and figure.source != source:
                continue
            self._visible_figures.append(figure)
            item = QListWidgetItem(f"{figure.source}  ·  {figure.title}")
            item.setData(Qt.UserRole, figure.filename)
            item.setToolTip(figure.purpose)
            self.figure_list.addItem(item)
            if figure.filename == current_filename:
                selected_item = item
        self.figure_count_label.setText(f"{len(self._visible_figures)} figures")
        if selected_item is None and self.figure_list.count():
            selected_item = self.figure_list.item(0)
        if selected_item is not None:
            self.figure_list.setCurrentItem(selected_item)
        else:
            self._show_figure(None)

    def _figure_selection_changed(self, current, _previous) -> None:
        if current is None:
            self._show_figure(None)
            return
        index = self.figure_list.row(current)
        figure = self._visible_figures[index] if 0 <= index < len(self._visible_figures) else None
        self._show_figure(figure)

    def _show_figure(self, figure: FigureDefinition | None) -> None:
        self._selected_figure = figure
        if figure is None:
            self.figure_title_label.setText("No matching figure")
            self.figure_source_badge.clear()
            self.figure_purpose_label.clear()
            self.figure_shows_label.clear()
            self.figure_interpretation_label.clear()
            self.figure_provenance_label.clear()
            self.open_figure_button.setEnabled(False)
            self.figure_docs_button.setEnabled(False)
            return
        self.figure_title_label.setText(figure.title)
        self.figure_source_badge.setText(figure.source)
        self.figure_purpose_label.setText(figure.purpose)
        self.figure_shows_label.setText(figure.shows)
        self.figure_interpretation_label.setText(figure.interpretation)
        self.figure_provenance_label.setText(figure.provenance)
        available = figure.asset_path.is_file()
        self.open_figure_button.setEnabled(available)
        self.figure_docs_button.setEnabled(True)
        if available:
            self.figure_preview.load(QByteArray(qt_safe_svg_bytes(figure.asset_path.read_bytes())))

    def _show_large_figure(self) -> None:
        figure = self._selected_figure
        if figure is None or not figure.asset_path.is_file():
            return
        if self._large_figure_dialog is not None:
            self._large_figure_dialog.close()
        dialog = SvgPreviewDialog(
            f"{figure.source} · {figure.title}",
            ((figure.title, figure.asset_path.read_bytes()),),
            self,
        )
        self._large_figure_dialog = dialog
        dialog.finished.connect(lambda _result, closed=dialog: self._figure_dialog_closed(closed))
        dialog.show()

    def _figure_dialog_closed(self, dialog: SvgPreviewDialog) -> None:
        if self._large_figure_dialog is dialog:
            self._large_figure_dialog = None

    def _open_figure_documentation(self) -> None:
        if self._selected_figure is not None:
            QDesktopServices.openUrl(QUrl(self._selected_figure.documentation_url))

    def _apply_filter(self) -> None:
        query_terms = self.search_edit.text().strip().casefold().split()
        view_filter = self.view_filter.currentText()
        source_filter = self.source_filter.currentText()
        current_item = self.parameter_tree.currentItem()
        selected_name = current_item.data(0, Qt.UserRole) if current_item else ""
        self.parameter_tree.clear()
        self._visible_definitions = []
        selected_item = None
        for catalog_index, definition in enumerate(self._definitions, start=1):
            if view_filter != "All views" and definition.view_mode != view_filter:
                continue
            if source_filter != "All sources" and definition.source != source_filter:
                continue
            display_name = definition.display_name or _display_parameter_name(definition.name)
            searchable = " ".join(
                (
                    str(catalog_index),
                    definition.name,
                    definition.source,
                    definition.view_mode,
                    definition.views,
                    definition.markers,
                    definition.calculation,
                    display_name,
                )
            ).casefold()
            if any(term not in searchable for term in query_terms):
                continue
            self._visible_definitions.append(definition)
            item = QTreeWidgetItem(
                (
                    str(catalog_index),
                    display_name,
                    definition.calculation,
                    definition.source,
                    definition.view_mode,
                    definition.views,
                )
            )
            item.setData(0, Qt.UserRole, definition.name)
            item.setToolTip(1, definition.name)
            item.setToolTip(2, definition.calculation)
            line_count = min(3, max(1, (len(definition.calculation) + 54) // 55))
            item.setSizeHint(2, QSize(0, 22 + (line_count - 1) * 16))
            self.parameter_tree.addTopLevelItem(item)
            if definition.name == selected_name:
                selected_item = item
        total = sum(
            (view_filter == "All views" or definition.view_mode == view_filter)
            and (source_filter == "All sources" or definition.source == source_filter)
            for definition in self._definitions
        )
        self.count_label.setText(f"Showing {len(self._visible_definitions)} of {total} gait parameters")
        if selected_item is None and self.parameter_tree.topLevelItemCount():
            selected_item = self.parameter_tree.topLevelItem(0)
        if selected_item is not None:
            self.parameter_tree.setCurrentItem(selected_item)
        else:
            self._show_definition(None)

    def _selection_changed(self, current, _previous) -> None:
        if current is None:
            self._show_definition(None)
            return
        index = self.parameter_tree.indexOfTopLevelItem(current)
        definition = self._visible_definitions[index] if 0 <= index < len(self._visible_definitions) else None
        self._show_definition(definition)

    def _show_definition(self, definition: GaitParameterDefinition | None) -> None:
        if definition is None:
            self.name_label.setText("No matching parameter")
            self.identifier_label.clear()
            self.views_label.clear()
            self.markers_label.clear()
            self.calculation_label.clear()
            return
        self.name_label.setText(definition.display_name or _display_parameter_name(definition.name))
        self.identifier_label.setText(definition.name)
        self.views_label.setText(definition.views)
        self.markers_label.setText(definition.markers)
        self.calculation_label.setText(definition.calculation)


def _detail_label(layout: QVBoxLayout, title: str) -> QLabel:
    heading = QLabel(title)
    heading.setObjectName("ParameterDetailHeading")
    layout.addWidget(heading)
    value = QLabel()
    value.setObjectName("ParameterDetailValue")
    value.setWordWrap(True)
    value.setTextInteractionFlags(Qt.TextSelectableByMouse)
    layout.addWidget(value)
    return value


def _figure_detail_label(layout: QVBoxLayout, title: str) -> QLabel:
    heading = QLabel(title)
    heading.setObjectName("FigureDetailHeading")
    layout.addWidget(heading)
    value = QLabel()
    value.setObjectName("FigureDetailValue")
    value.setWordWrap(True)
    value.setTextInteractionFlags(Qt.TextSelectableByMouse)
    layout.addWidget(value)
    return value


def _display_parameter_name(name: str) -> str:
    """Turn exported column identifiers into readable labels without changing the output name."""
    side, separator, remainder = name.partition("__")
    is_side_prefix = separator and side.casefold() in {"left", "right"}
    readable = (remainder if is_side_prefix else name).replace("_", " ")
    readable = " ".join(readable.split())
    if is_side_prefix:
        readable = f"{side.title()} · {readable}"
    return readable[:1].upper() + readable[1:] if readable else name


class GaitParameterSelectionWidget(QWidget):
    def __init__(
        self,
        enabled_parameter_names: tuple[str, ...] | None = None,
        *,
        multiside: bool = True,
    ):
        super().__init__()
        self.setObjectName("GaitParameterSelection")
        self._definitions = gait_parameter_catalog()
        self._multiside = multiside
        self._include_forelimb = False
        self._source_filter: str | None = None
        self._items: list[tuple[GaitParameterDefinition, QTreeWidgetItem]] = []
        layout = QVBoxLayout(self)
        layout.setContentsMargins(6, 6, 6, 6)
        layout.setSpacing(6)
        controls = QHBoxLayout()
        self.select_all_button = QPushButton("Select all")
        self.clear_button = QPushButton("Disable all")
        controls.addWidget(self.select_all_button)
        controls.addWidget(self.clear_button)
        layout.addLayout(controls)
        self.count_label = QLabel()
        self.count_label.setObjectName("MutedLabel")
        layout.addWidget(self.count_label)
        guidance = QLabel("Unchecked parameters are excluded from generated parameter tables and downstream analysis.")
        guidance.setObjectName("MutedLabel")
        guidance.setWordWrap(True)
        layout.addWidget(guidance)
        self.tree = QTreeWidget()
        self.tree.setObjectName("GaitParameterSelectionTree")
        self.tree.setHeaderLabels(("#", "Parameter", "Source"))
        self.tree.setRootIsDecorated(False)
        self.tree.header().setSectionResizeMode(0, QHeaderView.ResizeToContents)
        self.tree.header().setSectionResizeMode(1, QHeaderView.Stretch)
        self.tree.header().setSectionResizeMode(2, QHeaderView.ResizeToContents)
        enabled = set(enabled_parameter_names) if enabled_parameter_names is not None else None
        for index, definition in enumerate(self._definitions, start=1):
            item = QTreeWidgetItem((str(index), definition.name, definition.source))
            item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
            item.setCheckState(
                1,
                Qt.Checked if self._initially_enabled(definition, enabled) else Qt.Unchecked,
            )
            item.setToolTip(1, definition.calculation)
            self.tree.addTopLevelItem(item)
            self._items.append((definition, item))
        layout.addWidget(self.tree, 1)
        self.select_all_button.clicked.connect(lambda: self._set_all(Qt.Checked))
        self.clear_button.clicked.connect(lambda: self._set_all(Qt.Unchecked))
        self.tree.itemChanged.connect(self._update_count)
        self.set_multiside(multiside)

    @staticmethod
    def _initially_enabled(
        definition: GaitParameterDefinition,
        enabled: set[str] | None,
    ) -> bool:
        if enabled is None or definition.name in enabled:
            return True
        if definition.source != "ALMA":
            return False
        if definition.view_mode == "Multi-view":
            _side, separator, base_name = definition.name.partition("__")
            return bool(separator and base_name in enabled)
        return any(f"{side}__{definition.name}" in enabled for side in ("left", "right"))

    def set_multiside(self, multiside: bool) -> None:
        """Expose exactly the parameters generated by the selected input mode."""
        self._multiside = multiside
        expected_view_mode = "Multi-view" if multiside else "Single-view"
        forelimb_names = set(RUSTLAB1_FORELIMB_PARAMETER_NAMES)
        visible_index = 0
        for definition, item in self._items:
            visible = definition.view_mode == expected_view_mode and (
                self._include_forelimb or definition.name not in forelimb_names
            ) and (self._source_filter is None or definition.source == self._source_filter)
            item.setHidden(not visible)
            if visible:
                visible_index += 1
                item.setText(0, str(visible_index))
        self._update_count()

    def set_limb_scope(self, include_forelimb: bool) -> None:
        self._include_forelimb = bool(include_forelimb)
        self.set_multiside(self._multiside)

    def set_source_filter(self, source: str | None) -> None:
        """Limit the selectable rows to one analysis source, or show all sources."""
        self._source_filter = source
        self.set_multiside(self._multiside)

    def enabled_parameter_names(self) -> tuple[str, ...]:
        return tuple(
            definition.name
            for definition, item in self._items
            if not item.isHidden() and item.checkState(1) == Qt.Checked
        )

    def _set_all(self, state: Qt.CheckState) -> None:
        self.tree.blockSignals(True)
        for _definition, item in self._items:
            if not item.isHidden():
                item.setCheckState(1, state)
        self.tree.blockSignals(False)
        self._update_count()

    def _update_count(self, *_args) -> None:
        available = sum(not item.isHidden() for _definition, item in self._items)
        self.count_label.setText(
            f"{len(self.enabled_parameter_names())} of {available} parameters enabled"
        )


__all__ = [
    "FigureDefinition",
    "GaitParameterReferenceWidget",
    "GaitParameterSelectionWidget",
    "gait_figure_catalog",
]
